GET http://localhost:3000/
// GET All Users

###

GET http://localhost:3000/session
// GET All Users

###


////////////////////////////////////////////////////////
// USERS

GET http://localhost:3000/users
// GET All Users

###

GET http://localhost:3000/users/1
// GET User with id of 1

###

POST http://localhost:3000/users
content-type: application/json

{
  "username": "madhatter"
}

###

PUT http://localhost:3000/users/5
content-type: application/json

{
  "username": "moo"
}

###

DELETE http://localhost:3000/users/1

###


///////////////////////////////////////////////////////
// MESSAGES
GET http://localhost:3000/messages
// Get All messages

###

GET http://localhost:3000/messages/1
// Get message with id of 1

### 

GET http://localhost:3000/messages/438b2937-b584-4942-8661-4fc1a13ca1ab

### 

POST http://localhost:3000/messages
content-type: application/json

{
  "text": "This is a test message"
}

###

DELETE http://localhost:3000/messages/2