// Get All Users
GET http://localhost:3000/session

###

// Log In
POST http://localhost:3000/login
content-type: application/json

{
  "username": "eaglet",
  "password": "eaglet"
}

###

// Log Out
GET http://localhost:3000/logout
