// Get all messages
GET http://localhost:3000/messages

###

// Get messages for a specific user
GET http://localhost:3000/messages/1
// Get message with id of 1

### 


// Create a message (using the signed-in user)
POST http://localhost:3000/messages
content-type: application/json

{
  "text": "This is a test message"
}

###

// Update the message text
PUT http://localhost:3000/messages/7
content-type: application/json

{
  "text": "I have updated the text for message 7"
}

###

DELETE http://localhost:3000/messages/7